### ISSUE TITLE
Required headers for getHeaders()

### ISSUE THREAD

**Issue by adammbalogh** [raulferras/PHP-po-parser#40]
Is it a requirement for a `po` file to has some specific header? 

[https://github.com/raulferras/PHP-po-parser/blob/master/src/Sepia/PoParser.php#L745](https://github.com/raulferras/PHP-po-parser/blob/master/src/Sepia/PoParser.php#L745) 

If my `po`file contains only one header that is not valid?

**Comment by raulferras** [comment]
Well, reading the specification it is not clear to me if is there any mandatory header line.

On the other hand the `isHeader` method is only used to determine if an entry belongs to the header, but not if a po file is valid or not. However, it can happen a valid header not to be detected properly if it does not contain the headers `Project-Id-Version:`, `PO-Revision-Date:` and `MIME-Version:`...

I can change the logic because now that I see it, it doesn't look ok.

**Comment by adammbalogh** [comment]
> it can happen a valid header not to be detected properly if it does not contain the headers Project-Id-Version:, PO-Revision-Date: and MIME-Version:...

Correct, this is the problem.
