### ISSUE TITLE
How to fetch source string?

### ISSUE THREAD

**Issue by mickeyze** [raulferras/PHP-po-parser#75]
OK, it is possible to fetch translation for source with:

$entry = $catalog->getEntry('welcome.user');

but how to fetch source for translation?

Thanks,
M

**Comment by raulferras** [comment]
I don't fully understand your question. Can you elaborate?

**Comment by mickeyze** [comment]
Well, I made my .po file with following:

source: wordToBeTranslated
entry : translatedWord

However, in my project, I need to have both ways for checking data in .po file (it is complicated to explain why, so I will skip that part). From source to translation and vice versa. Sepia/PoParse version 4 allowed the option to export all sources+translations in a array which was suitable for Hash::combine and other array manipulations. However, with version 5 there is no such option because there is only export to array of Objects where json_encode and json_decode(array, true) returns empty string. 

Please, is there a way to support fetching both items (source from translation and translation from soruce) from .po file? 

Thanks,
M

**Comment by raulferras** [comment]
What I think you call `source` is `msgId` and your `entry` is `msgStr`.

Whenever you call `$catalog->getEntry('welcome.user')` you recieve an `Entry` object.  
Then you can query those parameters with:

```
$msgId = $entry->getMsgId();  
$msgStr = $entry->getMsgStr();
```

**Comment by mickeyze** [comment]
That will be nice if I would know what is my MsgID (welcome.user in your example). But if do not, I need to fetch all list of MsgStr, compare it with my string and then ask for MsgStr for defined MsgId. 
Any way to enable getMsgIdForMsgStr ?

**Comment by raulferras** [comment]
msgId is your source. In your previous example:
msgId: `wordToBeTranslated`
msgStr: `translatedWord`.

If you paste a sample of your .po file I can give you more details

**Comment by mickeyze** [comment]
ok, this is fine:
$msgId = 'wordToBeTranslated';
$catalog->getEntry($msgId);

Now, I have:
$msgStr = 'translatedWord';
is there a way to get: $catalog->getMsgId($msgStr);

**Comment by raulferras** [comment]
No, currently no and I don't think I will add such a method ever.
Basically, because the job of the `Catalog` is to be able to store a collection of entries and assign a unique identifier to each of them. This unique identifier is, by design in the PO format the content of the msgid. The msgstr cannot be considered unique (see two different msgid having the same text as translation). 

I'm not telling there is not a valid approach in what you try to do, but if you really need that you have two options:

1. Either call `Catalog::genEntries()`. You will receive an array of `Entry`'s that you can traverse and look for the desired entry using any of the methods available in `Entry`.
2. Implement your own Catalog (just extend `CatalogArray`) and implement a method like `getEntryByMsgStr`

But as I said,  is not guaranteed you will get just one Entry so code defensively against that.
